POST http://localhost:3000/users
Content-type: application/json

{
    "email": "fdddsddfdd@gmail.com"
}

###
GET http://localhost:3000/users

###
POST http://localhost:3000/events
Content-type: application/json

{
    "user": {
        "id": "89e63e3b-025c-415c-bd5e-96fd0a0d3040"
    },
    "consents": [{
        "id": "email_notifications",
        "enabled": true
    },{
        "id": "sms_notifications",
        "enabled": true
    }]
}
