POST http://localhost:3000/users
Content-type: application/json

{
    "email": "fdddsddfdd@gmail.com"
}

###
GET http://localhost:3000

###
POST http://localhost:3000/events
Content-type: application/json

{
    "user": {
        "id": "5cd69ebe-f7ff-4861-9a05-699414f0f403"
    },
    "consents": [{
        "id": "email_notifications",
        "enabled": false
    },{
        "id": "sms_notifications",
        "enabled": true
    }]
}
