apiVersion: apps/v1
kind: Deployment
metadata:
  name: didomi-app
  labels:
    app.kubernetes.io/name: didomi-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: didomi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: didomi-app
      name: didomi-app
    spec:
      securityContext: {}
      containers:
        - name: didomi-app
          image: didomi-app-image:latest
          env:
            - name: DB_URL_CONNECTION
              valueFrom:
                secretKeyRef:
                  key: DB_URL_CONNECTION
                  name: didomi-app-secret
            - name: DB_URL_TEST_CONNECTION
              valueFrom:
                secretKeyRef:
                  key: DB_URL_TEST_CONNECTION
                  name: didomi-app-secret
            - name: NODE_ENV
              value: production
            - name: API_VERSION
              value: v1
            - name: PORT
              value: "3000"

          # imagePullPolicy: Always # IfNotPresent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              ephemeral-storage: "10Mi"
            limits:
              memory: "512Mi"
              cpu: "200m"
              ephemeral-storage: "100Mi"
          securityContext:
            # https://kubernetes.io/docs/tasks/configure-pod-container/security-context
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 50000
            runAsGroup: 50000
