---
apiVersion: v1
kind: Service
metadata:
  name: didomi-app
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: didomi-app
  type: ClusterIP
  sessionAffinity: None
