@startuml

entity users {
    id (PK): varchar [40]
    email: varchar [100]
    created_at: datetime
    updated_at: datetime
}

entity events {
  id (PK): varchar[40]
  user_id (FK): varchar[40]
  name: enum ['email_notifications', 'sms_notifications']
  enabled: boolean
  created_at: datetime
  updated_at: datetime
}

entity events_history {
  id (PK): varchar[40]
  user_id (FK): varchar[40]
  name: enum ['email_notifications', 'sms_notifications']
  enabled: boolean
  created_at: datetime
}

users "1"--o{"*" events 
users "1"--o{"*" events_history
@enduml