# reference guide => https://docs.github.com/en/actions/learn-github-actions

name: ci-didomi-test

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        id: checkout

      - name: Set Up Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Lint
        id: lint
        run: npm run lint

      - name: Unit Test Code
        id: unit-test
        run: npm run test unit

      - name: Integration Test Code
        id: integration-test
        env:
          NODE_ENV: test
          POSTGRES_TEST_URL_CONNECTION: ${{ secrets.DB_URL_TEST_CONNECTION }}
        run: npm run migration:run && npm run test e2e
